### ISSUE TITLE
5.0 and 5.1 compatibility

### ISSUE THREAD

**Issue by awilliamson** [Yonaba/Lua-Class-System#3]
I know the module is written in the new standard but as Lua is extensively used as the scripting language of choice for modifying certain games, it would be nice for some backwards compatibility as some of those games only have Lua 5.1.

Would it be possible for you to make a branch for 5.0 and 5.1 module system?

**Comment by Yonaba** [comment]
Actually, LCS was made for Lua 5.1. That's the very first version of Lua I used myself and the one I do use the most. Most of the frameworks embedding Lua (nowadays) use at least this version, as far as I know.
I don't really know about Lua 5.0, and I am wondering if it's worth considering a Lua 5.0 patch [...](http://www.lua.org/manual/5.1/manual.html#7) ?

**Comment by awilliamson** [comment]
Hmm, well I'm writing for GarrysMod. Pretty sure it will only allow the use of module("lcs") in the actual module file rather than the return method.

I could be wrong, it may be using Lua 5.0, don't think it's explicitly stated anywhere. Thanks for the quick response though.

I love the way your lib is set out and would really like to use it, as a preferece over middleclass which doesn't want to cooperate with my current system.

**Comment by Yonaba** [comment]
Hmm. I made some research about that, and it came out that GMod seems to be [using a](http://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/indexd27d.html) [modified version of Lua 5.1](http://www.vim.org/scripts/script.php?script_id=3910). Modified here means that it doesn't implement every single functionnality of Lua's 5.1 standard libraries, but at least, [require](http://www.lua.org/pil/8.1.html) is supported in the way LCS expects it should. So, I don't feel any particular need to have support for Lua 5.0. 
Are there any other specific reasons you might want to come up with ? I'd love to hear them.

And of course, because LCS doesn't use the deprecated [module](http://lua-users.org/wiki/LuaModuleFunctionCritiqued) function, it should be compatible with further versions, I mean 5.2 and 5.3. Without any changes. Hopefully.

Very glad to know that you like it. I am thinking of making some extensions to this, when I have the chance. Be sure to check out [30log](https://github.com/Yonaba/30log) too, it also works nice, though it doesn't offer introspection methods such as `is_A`, nor static or abstract classes. That said, it isn't that hard to implement them on the top of that library.

**Comment by awilliamson** [comment]
everytime I do local LCS = require "LCS" even though I know the module is being included, the variable LCS is always nil, so I can't do anything with it. Any advice?

**Comment by Yonaba** [comment]
Hmm. I don't know much of GMod's environment, but you can try this:

``` lua
print(require('LCS'))
```

Note: Dunno if `print` is supported, but any equivalent (maybe [printMessage](http://gmodwiki.net/Lua/Global/PrintMessage)) should be fine.

What's the output ?
It might be related to the fact that LCS module returns actually a local. Maybe you should make it global by editing the file [LCS.lua](https://github.com/Yonaba/Lua-Class-System/blob/master/LCS.lua) and then require it this way:

``` lua
require('LCS')
```

**Comment by awilliamson** [comment]
Hmm nothing from the print, and same again when I attempt to return a global from the module. It could be the funky way that gmod is doing modules. Think you could implement a 'module' method solution?

**Comment by awilliamson** [comment]
Aha, making it a global does appear to have worked, slightly tacky making lcs equal the return but I guess I'll roll with it. I'll let you know how it goes.
